// people
export const REQUEST_FOR_PEOPLE = 'REQUEST_FOR_PEOPLE';
export const RESPONSE_FROM_PEOPLE = 'RESPONSE_FROM_PEOPLE';

// person
export const REQUEST_FOR_PERSON = 'REQUEST_FOR_PERSON';
export const RESPONSE_FROM_PERSON = 'RESPONSE_FROM_PERSON';
export const RESET_PERSON   = 'RESET_PERSON';

// species
export const REQUEST_FOR_SPECIES = 'REQUEST_FOR_SPECIES';
export const RESPONSE_FROM_SPECIES = 'RESPONSE_FROM_SPECIES';
export const RESET_SPECIES   = 'RESET_SPECIES';

// vehicles
export const REQUEST_FOR_VEHICLES = 'REQUEST_FOR_VEHICLES';
export const RESPONSE_FROM_VEHICLES = 'RESPONSE_FROM_VEHICLES';
export const RESET_VEHICLES   = 'RESET_VEHICLES';

// starships
export const REQUEST_FOR_STARSHIPS = 'REQUEST_FOR_STARSHIPS';
export const RESPONSE_FROM_STARSHIPS = 'RESPONSE_FROM_STARSHIPS';
export const RESET_STARSHIPS   = 'RESET_STARSHIPS';

// films
export const REQUEST_FOR_FILMS = 'REQUEST_FOR_FILMS';
export const RESPONSE_FROM_FILMS = 'RESPONSE_FROM_FILMS';
export const RESET_FILMS   = 'RESET_FILMS';

//
export const REQUEST_FOR_HOMEWORLD = 'REQUEST_FOR_HOMEWORLD';
export const RESPONSE_FROM_HOMEWORLD= 'RESPONSE_FROM_HOMEWORLD';
export const RESET_HOMEWORLD   = 'RESET_HOMEWORLD';
